#!/usr/bin/env bash

BOOKMARKS_PATH="$HOME/nixos/extras/bookmarks"

case "$1" in
  show)
    local link=$(dmenu -p 'Bookmark :: ' < "$BOOKMARKS_PATH")
    if test "$link"; then
      echo "open -t '$link'" >> "$QUTE_FIFO"
    fi
  ;;
  new)
    echo "$QUTE_URL" >> "$BOOKMARKS_PATH"
  ;;
  resource)
    ~/dev/projects/nvim-ts-peek/bin/nvim-peek dmenu "$QUTE_URL" "$QUTE_TITLE" \
      && notify-send "Saved $QUTE_URL";
  ;;
esac || true

