#!/usr/bin/env bash

trim() { sed '/^$/ d'; }

chromium_version="112";

useragents=`echo "
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/$chromium_version.0.3729.169 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/$chromium_version.0.3987.163 Safari/537.36
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/$chromium_version.0.4103.61 Chrome/$chromium_version.0.4103.61 Safari/537.36
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Brave Chrome/$chromium_version.0.3809.132 Safari/537.36
" | trim`;

ua=`echo -e "$useragents" | dmenu -p "User-agent ::"`;

[[ -z "$ua" ]] && exit 0;

echo "set content.headers.user_agent '$ua'" >> "$QUTE_FIFO";

