# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  boot.kernelParams = [ "i8042.nopnp=1" "pci=nocrs" "quiet" "splash" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d86af9a3-3627-4ed5-aa8c-152673d2397c";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2A7B-5D40";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/9884c440-8c3a-437f-a7b7-3c0d5bc7fe3f"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
