opener = """
  if [ -z "$DAFFM_SELECTIONS_OUT" ]; then
    echo "<cant open file>"
  else
    echo "%F" > "$DAFFM_SELECTIONS_OUT";
  fi
"""
extend = "@"

[keymap]
l = "open-and-quit"
"<cr>" = "open-and-quit"

[commands]
open-and-quit = [
  """eval [ -z $DAFFM_SELECTIONS_OUT ] || [ -d "$cursor" ] || echo '<daffm>quit' """,
  "open"
]
